# src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
         "//src/Library:Library",
         "//src/Book:Book",
         "//src/Functions:Functions"
    ],
    
)
