## src/studentfirstsessh/BUILD

cc_library(
    name = "studentfirstsessh",
    srcs = ["studentfirstsessh.cpp"],
    hdrs = ["studentfirstsessh.hpp"],
    visibility = ["//visibility:public"],
  deps = [
        "//src/Student:Student",
    ],
)
