## src/Functions/BUILD

cc_library(
    name = "Functions",
    srcs = ["functions.cpp"],
    hdrs = ["functions.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Train:Train"
    ],
)
