## src/studentsecondsessh/BUILD

cc_library(
    name = "studentsecondsessh",
    srcs = ["studentsecondsessh.cpp"],
    hdrs = ["studentsecondsessh.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Student:Student",
        "//src/studentfirstsessh:studentfirstsessh",
    ],
)
