## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/Student:Student",
        "//src/Person:Person",
        "//src/Professor:Professor",
    ],
)
